#!/bin/bash
POSTGRES_PORT=49533
echo "Creating a Postgres image running on"
docker build -t postgres_warehouse_dev postgres/

echo "Starting a container from the image"
docker run -d -P -p $POSTGRES_PORT:5432 --name postgres_warehouse_dev_container postgres_warehouse_dev
