#!/bin/bash

PROCESSES=$(docker ps -a --no-trunc | grep "postgres_warehouse_dev" | awk '{print $1}')

echo "Stopping and removing" $PROCESSES

docker stop $PROCESSES
docker rm $PROCESSES
echo "Deleting image"
docker rmi postgres_warehouse_dev
echo "Done!"
